apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-server
  labels:
    app: lab-server
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: lab-server
  template:
    metadata:
      labels:
        app: lab-server
    spec:
      containers:
        - image: ghcr.io/hpi-dhc/pharme-lab-server:main
          imagePullPolicy: "Always"
          name: lab-server
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: lab-server-db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: lab_server_db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: lab_server_db_pass
            - name: DB_NAME
              value: db
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ENDPOINT
              value: minio-service
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: minio_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: minio_pass
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_auth_url
            - name: KEYCLOAK_REALM
              value: pharme
            - name: KEYCLOAK_CLIENT_ID
              value: pharme-lab-server
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: lab-server-secrets
                  key: keycloak_secret


---
apiVersion: v1
kind: Service
metadata:
  name: svc-lab-server
  labels:
    app: lab-server
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: lab-server

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lab-server
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: lab-server-pharme.dhc-lab.hpi.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-lab-server
                port:
                  number: 3001
