name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  auto_route: ^3.0.4
  black_hole_flutter: ^0.3.4
  bloc: ^7.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  freezed_annotation: ^0.15.0
  http: ^0.13.4
  json_annotation: ^4.3.0

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
