name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.10.0 <2.11.0'

dependencies:
  auto_route: ^3.2.4
  black_hole_flutter: ^0.3.5
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  debug_overlay: ^0.1.3
  dropdown_button2: ^1.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  flutter_sliding_up_panel: ^2.0.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  openid_client: ^0.4.6
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_launcher_icons: '^0.9.2'
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
