name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0 <3.1.0'

dependencies:
  auto_route: ^4.2.0
  black_hole_flutter: ^0.3.5
  bloc: ^8.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  comprehension_measurement:
    git: 
      url: https://github.com/hpi-dhc/comprehension-measurement.git
      ref: main
  cupertino_icons: ^1.0.4
  dartx: ^1.1.0
  debug_overlay: ^0.1.4
  dropdown_button2: ^1.6.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_share: ^2.0.0
  flutter_sliding_up_panel: ^2.0.1
  flutter_svg: ^1.1.1
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  openid_client: ^0.4.6
  path_provider: ^2.0.11
  pdf: ^3.8.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
