name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+8

environment:
  sdk: '>=3.0.0 <3.3.0'
  flutter: '>=3.3.0'

dependencies:
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  black_hole_flutter: ^1.1.0
  bloc: ^8.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dartx: ^1.1.0
  debug_overlay: ^0.2.11
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.20.3
  flutter_list_view: ^1.1.22
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_share: ^2.0.0
  flutter_sliding_up_panel: ^2.0.1
  flutter_svg: ^2.0.9
  flutter_web_auth: ^0.5.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.0.3
  google_fonts: ^6.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^1.1.2
  intl: ^0.18.1
  json_annotation: ^4.6.0
  overlay_dialog: ^0.2.2
  path_provider: ^2.0.11
  pdf: ^3.8.1
  printing: ^5.9.3
  provider: ^6.1.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^1.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/tutorial/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
